# ascii-xfr
# Autogenerated from man page /usr/share/man/man1/ascii-xfr.1.gz
complete -c ascii-xfr -s s --description 'Send a file.'
complete -c ascii-xfr -s r --description 'Receive a file.  One of -s or -r must be present.'
complete -c ascii-xfr -s e --description 'Send the End-Of-File character (Control-Z, ASCII 26 by default) when uploadin…'
complete -c ascii-xfr -s d --description 'Use the Control-D (ASCII 4) as End-Of-File character.'
complete -c ascii-xfr -s n --description 'Do not translate CR to CRLF and vice versa.'
complete -c ascii-xfr -s v --description 'Verbose: show transfer statistics on the stderr output.'
complete -c ascii-xfr -s l --description 'When transmitting, pause for this delay after each line.'
complete -c ascii-xfr -s c --description 'When transmitting, pause for this delay after each character.'

