# atk6-fake_solicitate6
# Autogenerated from man page /usr/share/man/man8/atk6-fake_solicitate6.8.gz
complete -c atk6-fake_solicitate6 -s t --description 'Enumerates a domain for DNS entries, it uses a dictionary file if supplied or…'
complete -c atk6-fake_solicitate6 -s s -s d --description 'The hello command takes optionally the DR priority (default: 0).'
complete -c atk6-fake_solicitate6 -s T -s p -s 1 -s 2 -s 3 -s 4 -s 5 -s 6 -s 7 --description 'Fuzzes an icmp6 packet.'
complete -c atk6-fake_solicitate6 -s 8 -s 9 -s A -s B -s C -s D -s m -s f -s l -s v -s x -s c -s o --description 'Fuzzes messages sent to a DHCPv6 client.'
complete -c atk6-fake_solicitate6 -s e --description 'Fuzzes a DHCPv6 server on specified packet types.'
complete -c atk6-fake_solicitate6 -s h --description 'Note that on Debian (if you read this on Debian) command names are prefixed w…'
complete -c atk6-fake_solicitate6 -s a --description '.'
complete -c atk6-fake_solicitate6 -s P --description '.'
complete -c atk6-fake_solicitate6 -s U --description '.'
complete -c atk6-fake_solicitate6 -s r --description '.'
complete -c atk6-fake_solicitate6 -s R --description '.'

