# autopsy
# Autogenerated from man page /usr/share/man/man1/autopsy.1.gz
complete -c autopsy -s p --description 'is given, then the server opens on that port and if  addr is given, then conn…'
complete -c autopsy -s i --description 'argument is given, then autopsy goes into live analysis mode.'
complete -c autopsy -s c --description 'Force the program to use cookies even for localhost.'
complete -c autopsy -s C --description 'Force the program to not use cookies even for remote hosts.'
complete -c autopsy -s d --description 'Directory where cases and hosts are stored.'

