# boxes
# Autogenerated from man page /usr/share/man/man1/boxes.1.gz
complete -c boxes -s a --description 'Alignment/positioning of text inside box.'
complete -c boxes -s c --description 'Command line design definition for simple cases.'
complete -c boxes -s d --description 'Design selection.'
complete -c boxes -s f --description 'Use alternate config file.'
complete -c boxes -s h --description 'Print usage information.'
complete -c boxes -s i --description 'Indentation mode.'
complete -c boxes -s k --description 'Kill leading/trailing blank lines on removal.'
complete -c boxes -s l --description '(ell) List designs.'
complete -c boxes -s m --description 'Mend box.'
complete -c boxes -s p --description 'Padding.'
complete -c boxes -s r --description 'Remove box.  Removes an existing box instead of drawing it.'
complete -c boxes -s s --description 'Box size.'
complete -c boxes -s t --description 'Tab handling.'
complete -c boxes -s v --description 'Print out current version number.'

