# bundle-list
# Autogenerated from man page /usr/share/man/man1/bundle-list.1.gz
complete -c bundle-list -l name-only --description 'Print only the name of each gem.'
complete -c bundle-list -l paths --description 'Print the path to each gem in the bundle.'
complete -c bundle-list -l without-group --description 'Print all gems expect from a group.'

