# bundle-add
# Autogenerated from man page /usr/share/man/man1/bundle-add.1.gz
complete -c bundle-add -l version -s v --description 'Specify version requirements(s) for the added gem.'
complete -c bundle-add -l group -s g --description 'Specify the group(s) for the added gem.'
complete -c bundle-add -l source -s s --description 'Specify the source for the added gem.'
complete -c bundle-add -l git --description 'Specify the git source for the added gem.'
complete -c bundle-add -l branch --description 'Specify the git branch for the added gem.'
complete -c bundle-add -l skip-install --description 'Adds the gem to the Gemfile but does not install it.'
complete -c bundle-add -l optimistic --description 'Adds optimistic declaration of version .'

