# bundle-gem
# Autogenerated from man page /usr/share/man/man1/bundle-gem.1.gz
complete -c bundle-gem -l exe -s b -l bin --description 'Specify that Bundler should create a binary executable (as exe/GEM_NAME) in t…'
complete -c bundle-gem -l no-exe --description 'Do not create a binary (overrides --exe specified in the global config).'
complete -c bundle-gem -l coc --description 'Add a CODE_OF_CONDUCT. md file to the root of the generated project.'
complete -c bundle-gem -l no-coc --description 'Do not create a CODE_OF_CONDUCT.'
complete -c bundle-gem -l ext --description 'Add boilerplate for C extension code to the generated project.'
complete -c bundle-gem -l no-ext --description 'Do not add C extension code (overrides --ext specified in the global config).'
complete -c bundle-gem -l mit --description 'Add an MIT license to a LICENSE.'
complete -c bundle-gem -l no-mit --description 'Do not create a LICENSE. txt (overrides --mit specified in the global config).'
complete -c bundle-gem -s t -l test -l test --description 'Specify the test framework that Bundler should use when generating the projec…'

