# bundler
# Autogenerated from man page /usr/share/man/man1/bundler.1.gz
complete -c bundler -l no-color --description 'Print all output without color .'
complete -c bundler -l retry -s r --description 'Specify the number of times you wish to attempt network commands .'

