# cardos-tool
# Autogenerated from man page /usr/share/man/man1/cardos-tool.1.gz
complete -c cardos-tool -l card-driver -s c --description 'Use the card driver specified by name.'
complete -c cardos-tool -l format -s f --description 'Format the card or token.'
complete -c cardos-tool -l help -s h --description 'Print help message on screen.'
complete -c cardos-tool -l info -s i --description 'Display information about the card or token.'
complete -c cardos-tool -l reader -s r --description 'Number of the reader to use.'
complete -c cardos-tool -l startkey -s s --description 'Specify startkey for format.'
complete -c cardos-tool -l change-startkey -s S --description 'Change Startkey with given APDU command.'
complete -c cardos-tool -l verbose -s v --description 'Causes cardos-tool to be more verbose.'
complete -c cardos-tool -l wait -s w --description 'Causes cardos-tool to wait for the token to be inserted into reader.'

