# cava
# Autogenerated from man page /usr/share/man/man1/cava.1.gz
complete -c cava -s p --description '  Specifies path to alternative config file.'
complete -c cava -s v --description '  Prints version.'

