# cherryd3
# Autogenerated from man page /usr/share/man/man1/cherryd3.1.gz
complete -c cherryd3 -s c -l 'config\\fn' --description 'Specifies a config file which is to be read and merged into the CherryPy site…'
complete -c cherryd3 -s d --description 'Run the server as a daemon.'
complete -c cherryd3 -s e -l 'environment\\fn' --description 'Specifies the name of an environment to be applied.'
complete -c cherryd3 -s f --description 'Start a fastcgi server instead of the default HTTP server.'
complete -c cherryd3 -s s --description 'Start a scgi server instead of the default HTTP server.'
complete -c cherryd3 -s i -l 'import\\fn' --description 'Specifies a module to import.   This option may be specified multiple times.'
complete -c cherryd3 -s p -l 'pidfile\\fn' --description 'Store the process id in PIDFILE_PATH.'
complete -c cherryd3 -s P -l Path --description 'Specifies a directory to be inserted at the head of sys. path.'
complete -c cherryd3 -l config --description 'Specifies a config file which is to be read and merged into the CherryPy site…'
complete -c cherryd3 -l environment --description 'Specifies the name of an environment to be applied.'
complete -c cherryd3 -l import --description 'Specifies a module to import.   This option may be specified multiple times.'
complete -c cherryd3 -l pidfile --description 'Store the process id in PIDFILE_PATH.'

