# chntpw
# Autogenerated from man page /usr/share/man/man8/chntpw.8.gz
complete -c chntpw -s h --description 'Show a summary of options.'
complete -c chntpw -s u --description 'Username or username ID (RID) to change.  The default is \'Administrator\'.'
complete -c chntpw -s l --description 'List all users in the SAM database and exit.'
complete -c chntpw -s i --description 'Interactive Menu system: list all users (as per -l option) and then ask for t…'
complete -c chntpw -s e --description 'Registry editor with limited capabilities (but it does include write support).'
complete -c chntpw -s d --description 'Use buffer debugger instead (hex editor)   -L Log all changed filenames to /t…'
complete -c chntpw -s N --description 'Do not allocate more information, only allow the editing of existing values w…'
complete -c chntpw -s E --description 'Do not expand the hive file (safe mode).'
complete -c chntpw -s L --description 'Log all changed filenames to /tmp/changed.'
complete -c chntpw -s v --description 'Print verbose information and debug messages.  EXAMPLES.'

