# compress
# Autogenerated from man page /usr/share/man/man1/compress.1.gz
complete -c compress -s f --description 'flag is given.'
complete -c compress -s c --description 'option makes compress/uncompress.'
complete -c compress -s r --description 'flag is specified,  compress will operate recursively.'
complete -c compress -s V --description 'flag tells each of these programs to print its version and patchlevel, along …'
complete -c compress -s b --description 'flag is reached (default 16).  Bits must be between 9 and 16.'
complete -c compress -s v --description 'option, a message is printed yielding the percentage of reduction for each fi…'

