# debtags
# Autogenerated from man page /usr/share/man/man1/debtags.1.gz
complete -c debtags -s h -l help --description 'show this help message and exit.'
complete -c debtags -l version --description 'show program\'s version number and exit.'
complete -c debtags -l verbose -s v --description 'enable verbose output.'
complete -c debtags -l debug --description 'enable debugging output (including verbose output) .'

