# dirb-gendict
# Autogenerated from man page /usr/share/man/man1/dirb-gendict.1.gz
complete -c dirb-gendict -s n --description 'RB Specify a numeric [0-9] input pattern.'
complete -c dirb-gendict -s c --description 'RB Specify an alphabetic [a-z] input pattern.'
complete -c dirb-gendict -s C --description 'RB Specify an uppercase alphabetic [A-Z] input pattern.'
complete -c dirb-gendict -s h --description 'RB  Specify an hexadecimal [0-f] input pattern.'
complete -c dirb-gendict -s a --description 'RB Specify an alphanumeric [0-9a-z] input pattern.'
complete -c dirb-gendict -s s --description 'RB Specify an alphanumeric case sensitive [0-9a-zA-Z] input pattern.'

