# dmenu_run
# Autogenerated from man page /usr/share/man/man1/dmenu_run.1.gz
complete -c dmenu_run -s b --description 'dmenu appears at the bottom of the screen.'
complete -c dmenu_run -s f --description 'dmenu grabs the keyboard before reading stdin if not reading from a tty.'
complete -c dmenu_run -s i --description 'dmenu matches menu items case insensitively.'
complete -c dmenu_run -s l --description 'dmenu lists items vertically, with the given number of lines.'
complete -c dmenu_run -s m --description 'dmenu is displayed on the monitor number supplied.'
complete -c dmenu_run -s p --description 'defines the prompt to be displayed to the left of the input field.'
complete -c dmenu_run -o fn --description 'defines the font or font set used.'
complete -c dmenu_run -o nb --description 'defines the normal background color.'
complete -c dmenu_run -o nf --description 'defines the normal foreground color.'
complete -c dmenu_run -o sb --description 'defines the selected background color.'
complete -c dmenu_run -o sf --description 'defines the selected foreground color.'
complete -c dmenu_run -s v --description 'prints version information to stdout, then exits.'
complete -c dmenu_run -s w --description 'embed into windowid.  USAGE dmenu is completely controlled by the keyboard.'

