# dnie-tool
# Autogenerated from man page /usr/share/man/man1/dnie-tool.1.gz
complete -c dnie-tool -l idesp -s i --description 'Show the DNIe IDESP value.'
complete -c dnie-tool -l data -s d --description 'Show DNIe personal information.'
complete -c dnie-tool -l all -s a --description 'Displays every available information.'
complete -c dnie-tool -l serial -s s --description 'Displays DNIe Serial Number.'
complete -c dnie-tool -l version -s V --description 'Show DNIe sw version.  Displays software version for in-card DNIe OS.'
complete -c dnie-tool -l pin -s p --description 'Specify the user pin pin to use.'
complete -c dnie-tool -l reader -s r --description 'Number of the reader to use.'
complete -c dnie-tool -l driver -s c --description 'Specify the card driver driver to use.'
complete -c dnie-tool -l wait -s w --description 'Causes dnie-tool to wait for the token to be inserted into reader.'
complete -c dnie-tool -l verbose -s v --description 'Causes dnie-tool to be more verbose.'

