# dnstap-read
# Autogenerated from man page /usr/share/man/man1/dnstap-read.1.gz
complete -c dnstap-read -s m --description 'Trace memory allocations; used for debugging memory leaks.'
complete -c dnstap-read -s p --description 'After printing the dnstap data, print the text form of the DNS message that w…'
complete -c dnstap-read -s x --description 'After printing the dnstap data, print a hex dump of the wire form of the DNS …'
complete -c dnstap-read -s y --description 'Print dnstap data in a detailed YAML format.'

