# eepget
# Autogenerated from man page /usr/share/man/man1/eepget.1.gz
complete -c eepget -s c --description '.'
complete -c eepget -s e --description '.'
complete -c eepget -s h --description '.'
complete -c eepget -s l --description '.'
complete -c eepget -s m --description '.'
complete -c eepget -s n --description '.'
complete -c eepget -s o --description '.'
complete -c eepget -s p --description '.'
complete -c eepget -s t --description '.'
complete -c eepget -s u --description '.'
complete -c eepget -s x --description '.'

