# egk-tool
# Autogenerated from man page /usr/share/man/man1/egk-tool.1.gz
complete -c egk-tool -l help -s h --description 'Print help and exit.'
complete -c egk-tool -l version -s V --description 'Print version and exit.'
complete -c egk-tool -l reader -s r --description 'Number of the reader to use.'
complete -c egk-tool -l verbose -s v --description 'Causes egk-tool to be more verbose.'
complete -c egk-tool -l pd --description 'Show \\*(AqPersÃ¶nliche Versicherungsdaten\\*(Aq (XML).'
complete -c egk-tool -l vd --description 'Show \\*(AqAllgemeine Versicherungsdaten\\*(Aq (XML).'
complete -c egk-tool -l gvd --description 'Show \\*(AqGeschÃ¼tzte Versicherungsdaten\\*(Aq (XML).'
complete -c egk-tool -l vsd-status --description 'Show \\*(AqVersichertenstammdaten-Status\\*(Aq.'

