# eidenv
# Autogenerated from man page /usr/share/man/man1/eidenv.1.gz
complete -c eidenv -l exec -s x --description 'Executes the given program with data in environment variables.'
complete -c eidenv -l help -s h --description 'Print help message on screen.'
complete -c eidenv -l print -s p --description 'Prints all data fields from the card, like validity period, document number e…'
complete -c eidenv -l reader -s r --description 'Number of the reader to use.'
complete -c eidenv -l stats -s t --description 'Prints key usage statistics (only for Estonian ID card).'
complete -c eidenv -l version -s v --description 'Prints the version of the utility and exits.'
complete -c eidenv -l wait -s w --description 'Wait for a card to be inserted.'

