# exfatfsck
# Autogenerated from man page /usr/share/man/man8/exfatfsck.8.gz
complete -c exfatfsck -s a --description 'Automatically repair the file system.  No user intervention required.'
complete -c exfatfsck -s n --description 'No-operation mode: non-interactively check for errors, but don\'t write anythi…'
complete -c exfatfsck -s p --description 'Same as -a for compatibility with other *fsck.'
complete -c exfatfsck -s V --description 'Print version and copyright.'
complete -c exfatfsck -s y --description 'Same as -a for compatibility with other *fsck.'

