# faraday-server
# Autogenerated from man page /usr/share/man/man1/faraday-server.1.gz
complete -c faraday-server -s h -l help --description 'show this help message and exit.'
complete -c faraday-server -l ssl --description 'enable HTTPS.'
complete -c faraday-server -l debug --description 'run Faraday Server in debug mode.'
complete -c faraday-server -l start --description 'run Faraday Server in background.'
complete -c faraday-server -l stop --description 'stop Faraday Server.'
complete -c faraday-server -l restart --description 'Restart Faraday Server.'
complete -c faraday-server -l port --description 'Overrides server. ini port configuration.'
complete -c faraday-server -l websocket_port --description 'Overrides server. ini websocket port configuration.'
complete -c faraday-server -l bind_address --description 'Overrides server. ini bind_address configuration.'
complete -c faraday-server -s v -l version --description 'show program\'s version number and exit SEE ALSO /usr/share/doc/python-faraday…'

