# florence
# Autogenerated from man page /usr/share/man/man1/florence.1.gz
complete -c florence -s h -l help --description 'Print help message and exit.'
complete -c florence -s V -l version --description 'Print Florence version and exit.'
complete -c florence -s c -l config --description 'Open configuration dialog.'
complete -c florence -s d -l debug --description 'Launch Florence in verbose mode.'
complete -c florence -s n -l no-gnome --description 'Use this option if you are not using the GNOME desktop environment.'
complete -c florence -s f -l focus --description 'With this option, any florence input will go to the selected window.'
complete -c florence -s u -l use-config --description 'Use the configuration file provided instead of gconf.'

