# fplugin
# Autogenerated from man page /usr/share/man/man1/fplugin.1.gz
complete -c fplugin -s h -l help --description 'show this help message and exit.'
complete -c fplugin -s i -l interactive --description 'Run in interactive mode (default: False).'
complete -c fplugin -s w -l workspace --description 'Workspace to use (default: untitled).'
complete -c fplugin -s u -l url --description 'Faraday Server URL.'
complete -c fplugin -l username --description '.'
complete -c fplugin -l password --description 'AVAILABLE SCRIPTS.'

