# futility
# Autogenerated from man page /usr/share/man/man1/futility.1.gz
complete -c futility -l vb1 --description 'Use only vboot v1. 0 binary formats.'
complete -c futility -l vb21 --description 'Use only vboot v2. 1 binary formats.'
complete -c futility -l debug --description 'Be noisy about what\'s going on . PP The following commands are built-in:.'

