# gids-tool
# Autogenerated from man page /usr/share/man/man1/gids-tool.1.gz
complete -c gids-tool -s X -l initialize --description 'Initialize token.'
complete -c gids-tool -l admin-key --description 'Define the administrator key.'
complete -c gids-tool -l pin --description 'Define user PIN.'
complete -c gids-tool -l serial-number --description 'Define serial number.'
complete -c gids-tool -s U -l unblock --description 'Unblock the user PIN after an administrator authentication.'
complete -c gids-tool -s C -l change-admin-key --description 'Change the administrator key.'
complete -c gids-tool -l new-admin-key --description 'Define the new administrator key.'
complete -c gids-tool -l reader -s r --description 'Number of the reader to use.'
complete -c gids-tool -s w -l wait --description 'Wait for a card to be inserted.'
complete -c gids-tool -s v -l verbose --description 'Verbose operation.  Use several times to enable debug output.'

