# hexeditor
# Autogenerated from man page /usr/share/man/man1/hexeditor.1.gz
complete -c hexeditor -s h -l help --description 'Display help.'
complete -c hexeditor -s 8 -l highbit --description 'Display 8-bit text.'
complete -c hexeditor -s a -l alltext --description 'Display all text regardless that you know better.'
complete -c hexeditor -s b -l buffer --description 'Buffer the entire file into memory.   Faster, and enables insert and delete.'
complete -c hexeditor -s d -l disk --description 'File editing is a disk.   OpenBSD and Linux only.'
complete -c hexeditor -s f -l force --description 'Force editing of a disk.   Need this option to enable writing to disks.'
complete -c hexeditor -s q -l quiet --description 'Quiet Mode; Turn off all beeping.'
complete -c hexeditor -s r -l readonly --description 'Do not allow modifying the file.'
complete -c hexeditor -s v -l version --description 'Display version number.'

