# i2cdump
# Autogenerated from man page /usr/share/man/man8/i2cdump.8.gz
complete -c i2cdump -s V --description 'Display the version and exit.'
complete -c i2cdump -s f --description 'Force access to the device even if it is already busy.'
complete -c i2cdump -s r --description 'Limit the range of registers being accessed.'
complete -c i2cdump -s y --description 'Disable interactive mode.'
complete -c i2cdump -s a --description 'Allow using addresses between 0x00 - 0x02 and 0x78 - 0x7f.  Not recommended.'

