# i2cdetect
# Autogenerated from man page /usr/share/man/man8/i2cdetect.8.gz
complete -c i2cdetect -s y --description 'Disable interactive mode.'
complete -c i2cdetect -s a --description 'Force scanning of non-regular addresses.  Not recommended.'
complete -c i2cdetect -s q --description 'Use SMBus "quick write" command for probing.  Not recommended.'
complete -c i2cdetect -s r --description 'Use SMBus "receive byte" command for probing.  Not recommended.'
complete -c i2cdetect -s F --description 'Display the list of functionalities implemented by the adapter and exit.'
complete -c i2cdetect -s V --description 'Display the version and exit.'
complete -c i2cdetect -s l --description 'Output a list of installed busses.'

