# i2cget
# Autogenerated from man page /usr/share/man/man8/i2cget.8.gz
complete -c i2cget -s V --description 'Display the version and exit.'
complete -c i2cget -s f --description 'Force access to the device even if it is already busy.'
complete -c i2cget -s y --description 'Disable interactive mode.'
complete -c i2cget -s a --description 'Allow using addresses between 0x00 - 0x02 and 0x78 - 0x7f.  Not recommended.'

