# iasecc-tool
# Autogenerated from man page /usr/share/man/man1/iasecc-tool.1.gz
complete -c iasecc-tool -l reader --description 'Number of the reader to use.'
complete -c iasecc-tool -l list-applications --description 'Get list of the on-card applications.'
complete -c iasecc-tool -l aid --description 'Select hex-aid before processing.'
complete -c iasecc-tool -l list-sdos --description 'List SDOs of the given sdo-type, present in default or selected application.'
complete -c iasecc-tool -l verbose -s v --description 'Causes cardos-tool to be more verbose.'
complete -c iasecc-tool -l wait -s w --description 'Causes iasecc-tool to wait for the token to be inserted into reader.'

