# inetd2rlinetd
# Autogenerated from man page /usr/share/man/man8/inetd2rlinetd.8.gz
complete -c inetd2rlinetd -s f --description 'File in  inetd. conf (5) format which will be converted.  Default in stdin.'
complete -c inetd2rlinetd -s l --description 'A line in  inetd. conf (5) format.  Only that line will be converted.'
complete -c inetd2rlinetd -l force-overwrite --description 'Forces overwriting existing files with new version.'
complete -c inetd2rlinetd -l print-file-names --description 'Prints to standard output list of generated files.'
complete -c inetd2rlinetd -l add-from-comment --description 'Puts special comment with original inetd.'

