# iodine-client-start
# Autogenerated from man page /usr/share/man/man8/iodine-client-start.8.gz
complete -c iodine-client-start -s h -l help --description 'Print help and exit.'
complete -c iodine-client-start -s v -l version --description 'Print version info and exit.'

