# kismetdb_dump_devices
# Autogenerated from man page /usr/share/man/man1/kismetdb_dump_devices.1.gz
complete -c kismetdb_dump_devices -s i -l in --description 'Input kismetdb file.'
complete -c kismetdb_dump_devices -s o -l out --description 'Output Wigle CSV file.'
complete -c kismetdb_dump_devices -s f -l force --description 'Force writing to the target file, even if it exists.'
complete -c kismetdb_dump_devices -s e -l ekjson --description 'Write as ekjson records, one device per line, instead of as a complete JSON a…'
complete -c kismetdb_dump_devices -s v -l verbose --description 'Verbose output.'
complete -c kismetdb_dump_devices -s s -l skip-clean --description 'Don\'t clean (sql vacuum) input database SEE ALSO The full documentation for K…'

