# kismetdb_strip_packets
# Autogenerated from man page /usr/share/man/man1/kismetdb_strip_packets.1.gz
complete -c kismetdb_strip_packets -s i -l in --description 'Input kismetdb file.'
complete -c kismetdb_strip_packets -s o -l out --description 'Output kismetdb file with packet content stripped.'
complete -c kismetdb_strip_packets -s v -l verbose --description 'Verbose output.'
complete -c kismetdb_strip_packets -s f -l force --description 'Force writing to the target file, even if it exists.'

