# kismetdb_statistics
# Autogenerated from man page /usr/share/man/man1/kismetdb_statistics.1.gz
complete -c kismetdb_statistics -s i -l in --description 'Input kismetdb file.'
complete -c kismetdb_statistics -s s -l skip-clean --description 'Don\'t clean (sql vacuum) input database.'
complete -c kismetdb_statistics -s j -l json --description 'Dump stats as a JSON dictionary SEE ALSO The full documentation for Kismet is…'

