# libnpx
# Autogenerated from man page /usr/share/man/man1/libnpx.1.gz
complete -c libnpx -s p -l package -l package --description 'o 2.'
complete -c libnpx -l no-install --description 'o 2.'
complete -c libnpx -l cache --description 'o 2.'
complete -c libnpx -l userconfig --description 'o 2.'
complete -c libnpx -s c --description 'o 2.'
complete -c libnpx -l shell --description 'o 2.'
complete -c libnpx -l shell-auto-fallback --description 'o 2.'
complete -c libnpx -l ignore-existing --description 'o 2.'
complete -c libnpx -s q -l quiet --description 'o 2.'
complete -c libnpx -s n -l node-arg --description 'o 2.'
complete -c libnpx -s v -l version --description 'EXAMPLES Running a project-local bin $ npm i -D webpack $ npx webpack .'

