# llvm-size-9
# Autogenerated from man page /usr/share/man/man1/llvm-size-9.1.gz
complete -c llvm-size-9 -l common --description 'When using Berkely format, this is added to bss.'
complete -c llvm-size-9 -l help -l help-hidden --description '.'
complete -c llvm-size-9 -l help-list -l help-list-hidden --description '.'
complete -c llvm-size-9 -l version --description '.'
complete -c llvm-size-9 -s A --description '.'
complete -c llvm-size-9 -s B --description '.'
complete -c llvm-size-9 -s m -s m --description '.'
complete -c llvm-size-9 -l arch --description '.'
complete -c llvm-size-9 -l format --description '.'
complete -c llvm-size-9 -s l --description 'Print size in radix:.'
complete -c llvm-size-9 -s o --description '.'
complete -c llvm-size-9 -s d --description '.'
complete -c llvm-size-9 -s x --description '.'
complete -c llvm-size-9 -l radix --description '.'
complete -c llvm-size-9 -l totals --description '.'

