# miredo-checkconf
# Autogenerated from man page /usr/share/man/man8/miredo-checkconf.8.gz
complete -c miredo-checkconf -s h -l help --description 'Display some help and exit.'
complete -c miredo-checkconf -s V -l version --description 'Display program version and exit.'

