# miredo
# Autogenerated from man page /usr/share/man/man8/miredo.8.gz
complete -c miredo -s c -l config --description 'Specify an alternate configuration file for Miredo instead of the .'
complete -c miredo -s f -l foreground --description 'Do not detach from the console.  Run the program in the foreground.'
complete -c miredo -s h -l help --description 'Display some help and exit.'
complete -c miredo -s t -l chrootdir --description 'Specify a directory to use as a root after initialization is completed.'
complete -c miredo -s u -l user --description 'Override the user that the program will run as.'
complete -c miredo -s V -l version --description 'Display program version and license and exit.'

