# mousepad
# Autogenerated from man page /usr/share/man/man1/mousepad.1.gz
complete -c mousepad -s h -l help --description 'Show help options.'
complete -c mousepad -l help-all --description 'Show all help options.'
complete -c mousepad -l help-gtk --description 'Show GTK+ Options.'
complete -c mousepad -l class --description 'Program class as used by the window manager.'
complete -c mousepad -l name --description 'Program name as used by the window manager.'
complete -c mousepad -l screen --description 'X screen to use.'
complete -c mousepad -l sync --description 'Make X calls synchronous.'
complete -c mousepad -l gtk-module --description 'Load additional GTK+ modules.'
complete -c mousepad -l g-fatal-warnings --description 'Make all warnings fatal Application Options:.'
complete -c mousepad -l disable-server --description 'Do not register with the D-BUS session message bus.'
complete -c mousepad -s q -l quit --description 'Quit a running Mousepad instance.'
complete -c mousepad -s v -l version --description 'Print version information and exit.'
complete -c mousepad -l display --description 'X display to use COPYRIGHT Copyright © 2007 The Xfce development team.'

