# mp32
# Autogenerated from man page /usr/share/man/man1/mp32.1.gz
complete -c mp32 -s V -l version --description 'Print version.'
complete -c mp32 -s h -l help --description 'Print help . PP * Increment:.'
complete -c mp32 -s i -l increment --description 'Enable increment mode.'
complete -c mp32 -l combinations --description 'Calculate number of combinations.'
complete -c mp32 -l hex-charset --description 'Assume charset is given in hex.'
complete -c mp32 -s q -l seq-max --description 'Maximum number of multiple sequential characters.'
complete -c mp32 -s r -l occurrence-max --description 'Maximum number of occurrence of a character . PP * Resources:.'
complete -c mp32 -s s -l start-at --description 'Start at specific position.'
complete -c mp32 -s l -l stop-at --description 'Stop at specific position . PP * Files:.'
complete -c mp32 -s o -l output-file --description 'Output-file . PP * Custom charsets:.'
complete -c mp32 -s 1 -l custom-charset1 --description 'User-defineable charsets.'
complete -c mp32 -s 2 -l custom-charset2 --description 'Example: . HP -3,  --custom-charset3=\\,CS\\/  --custom-charset1=?dabcdef.'
complete -c mp32 -s 3 -l custom-charset3 --description '.'
complete -c mp32 -s 4 -l custom-charset4 --description 'sets charset ?1 to 0123456789abcdef.'

