# nokogiri
# Autogenerated from man page /usr/share/man/man1/nokogiri.1.gz
complete -c nokogiri -l type --description 'Set the type of the document to be parsed.'
complete -c nokogiri -s E -l encoding --description 'Set the encoding of the document.'
complete -c nokogiri -s e --description 'Specifies script from command-line.'
complete -c nokogiri -l rng --description 'Validate using this rng file.'
complete -c nokogiri -s '?' -l help --description 'Show a message very similar to this man page.'

