# onesixtyone
# Autogenerated from man page /usr/share/man/man1/onesixtyone.1.gz
complete -c onesixtyone -s i --description 'file with target hosts.'
complete -c onesixtyone -s o --description 'output log.'
complete -c onesixtyone -s p --description 'specify an alternate destination SNMP port.'
complete -c onesixtyone -s d --description 'debug mode, use twice for more information.'
complete -c onesixtyone -s s --description 'short mode, only print IP addresses.'
complete -c onesixtyone -s w --description 'wait n milliseconds (1/1000 of a second) between sending packets (default 10).'
complete -c onesixtyone -s q --description 'quiet mode, do not print log to stdout, use with -l .'
complete -c onesixtyone -s c --description '.'

