# opensc-notify
# Autogenerated from man page /usr/share/man/man1/opensc-notify.1.gz
complete -c opensc-notify -l help -s h --description 'Print help and exit.'
complete -c opensc-notify -l version -s V --description 'Print version and exit.'
complete -c opensc-notify -l title -s t --description 'Specify the title of the notification.'
complete -c opensc-notify -l message -s m --description 'Specify the main text of the notification.'
complete -c opensc-notify -l notify-card-inserted -s I --description 'See notify_card_inserted in opensc. conf (default=off).'
complete -c opensc-notify -l notify-card-removed -s R --description 'See notify_card_removed in opensc. conf (default=off).'
complete -c opensc-notify -l notify-pin-good -s G --description 'See notify_pin_good in opensc. conf (default=off).'
complete -c opensc-notify -l notify-pin-bad -s B --description 'See notify_pin_bad in opensc. conf (default=off).'

