# opensc-explorer
# Autogenerated from man page /usr/share/man/man1/opensc-explorer.1.gz
complete -c opensc-explorer -l card-driver -s c --description 'Use the given card driver.  The default is auto-detected.'
complete -c opensc-explorer -l mf -s m --description 'Select the file referenced by the given path on startup.'
complete -c opensc-explorer -l reader -s r --description 'Number of the reader to use.'
complete -c opensc-explorer -l verbose -s v --description 'Cause opensc-explorer to be more verbose.'
complete -c opensc-explorer -l wait -s w --description 'Wait for a card to be inserted.'

