# parse-edid
# Autogenerated from man page /usr/share/man/man1/parse-edid.1.gz
complete -c parse-edid -s b -l bus --description 'only scan the i2c bus BUS (if built with i2c support).'
complete -c parse-edid -s c -l classiconly --description 'only use the older VBE interface (if built with i2c and VBE support).'
complete -c parse-edid -s h -l help --description 'display a basic help message.'
complete -c parse-edid -s i -l i2conly --description 'only use the newer i2c interface (if built with i2c and VBE support).'
complete -c parse-edid -s m -l monitor --description 'try to return information about monitor number NUM (VBE only).'
complete -c parse-edid -s q -l quiet --description 'do not output messages over stderr.'

