# paster3
# Autogenerated from man page /usr/share/man/man1/paster3.1.gz
complete -c paster3 -s h -l help --description 'Show summary of options.'
complete -c paster3 -l version --description 'Show version of program.'
complete -c paster3 -l plugin --description 'Add a plugin to the list of commands (plugins are Egg specs; will also requir…'

