# pgcli
# Autogenerated from man page /usr/share/man/man1/pgcli.1.gz
complete -c pgcli -s h -l hostTEXT --description 'Host address of the postgres database.'
complete -c pgcli -s p -l portINTEGER --description 'Port number at which the postgres instance is listening.'
complete -c pgcli -s U -l userTEXT --description 'User name to connect to the postgres database.'
complete -c pgcli -s W -l password --description 'Force password prompt.'
complete -c pgcli -s w -l no-password --description 'Never prompt for password.'
complete -c pgcli -s v -l version --description 'Version of pgcli.'
complete -c pgcli -s d -l dbname --description 'Database name to connect to.'
complete -c pgcli -l pgclirc --description 'Location of pgclirc file.'
complete -c pgcli -l host --description 'Host address of the postgres database.'
complete -c pgcli -l port --description 'Port number at which the postgres instance is listening.'
complete -c pgcli -l user --description 'User name to connect to the postgres database.'
complete -c pgcli -l help --description 'Show this message and exit.'

