# piv-tool
# Autogenerated from man page /usr/share/man/man1/piv-tool.1.gz
complete -c piv-tool -l serial --description 'Print the card serial number derived from the CHUID object, if any.'
complete -c piv-tool -l name -s n --description 'Print the name of the inserted card (driver).'
complete -c piv-tool -l admin -s A --description 'Authenticate to the card using a 2DES or 3DES key.  The argument of the form .'
complete -c piv-tool -l genkey -s G --description 'Generate a key pair on the card and output the public key.'
complete -c piv-tool -l object -s O --description 'Load an object onto the card.'
complete -c piv-tool -l cert -s C --description 'Load a certificate onto the card.  ref is 9A, 9C, 9D or 9E.'
complete -c piv-tool -l compresscert -s Z --description 'Load a certificate that has been gzipped onto the card.'
complete -c piv-tool -l out -s o --description 'Output file for any operation that produces output.'
complete -c piv-tool -l in -s i --description 'Input file for any operation that requires an input file.'
complete -c piv-tool -l key-slots-discovery --description 'Print properties of the key slots.  Needs \\*(Aqadmin\\*(Aq authentication.'
complete -c piv-tool -l send-apdu -s s --description 'Sends an arbitrary APDU to the card in the format AA:BB:CC:DD:EE:FF.'
complete -c piv-tool -l reader -s r --description 'Number of the reader to use.'
complete -c piv-tool -l card-driver -s c --description 'Use the given card driver.  The default is auto-detected.'
complete -c piv-tool -l wait -s w --description 'Wait for a card to be inserted.'
complete -c piv-tool -l verbose -s v --description 'Causes piv-tool to be more verbose.'

