# pt2to3
# Autogenerated from man page /usr/share/man/man1/pt2to3.1.gz
complete -c pt2to3 -s r -l reverse --description 'Reverts changes, going from 3. x -> 2. x.'
complete -c pt2to3 -s p -l no-ignore-previous --description 'Ignores previous_api() calls.'
complete -c pt2to3 -s o --description 'Output file to write to.'
complete -c pt2to3 -s i -l inplace --description 'Overwrites the file in-place.'
complete -c pt2to3 -s h --description 'Print help on usage.  SEE ALSO ptrepack (1), ptdump (1).'

