# ptdump
# Autogenerated from man page /usr/share/man/man1/ptdump.1.gz
complete -c ptdump -s d --description 'Dump data information on leaves.'
complete -c ptdump -s v --description 'Dump more metainformation on nodes.'
complete -c ptdump -s a --description 'Show attributes in nodes (only useful when -v or -d are active).'
complete -c ptdump -s c --description 'Show info of columns in tables (only useful when -v or -d are active).'
complete -c ptdump -s i --description 'Show info of indexed column (only useful when -v or -d are active).'
complete -c ptdump -s R --description 'Select a range of rows in the form "start,stop,step" for all leaves.'
complete -c ptdump -s h --description 'Print help on usage.  SEE ALSO ptrepack (1).'

