# pttree
# Autogenerated from man page /usr/share/man/man1/pttree.1.gz
complete -c pttree -s L -l max-level --description 'maximum branch depth of tree to display (-1 == no limit).'
complete -c pttree -s S -l sort-by --description 'artificially order nodes, can be either "size", "name" or "none".'
complete -c pttree -l print-size --description 'print size of each node/branch.'
complete -c pttree -l print-shape --description 'print shape of each node.'
complete -c pttree -l print-compression --description 'print compression library(level) for each compressed node.'
complete -c pttree -l print-percent --description 'print size of each node as a % of the total tree size on disk.'
complete -c pttree -l use-si-units --description 'report sizes in SI units (1 MB == 10^6 B).'
complete -c pttree -l use-binary-units --description 'report sizes in binary units (1 MiB == 2^20 B).'
complete -c pttree -l no-print-size --description '.'
complete -c pttree -l no-print-shape --description '.'
complete -c pttree -l no-print-compression --description '.'
complete -c pttree -l no-print-percent --description '.'
complete -c pttree -s h --description 'Print help on usage.  SEE ALSO ptdump (1).'

