# pwgen
# Autogenerated from man page /usr/share/man/man1/pwgen.1.gz
complete -c pwgen -s 0 -l no-numerals --description 'Don\'t include numbers in the generated passwords.'
complete -c pwgen -s 1 --description 'Print the generated passwords one per line.'
complete -c pwgen -s A -l no-capitalize --description 'Don\'t bother to include any capital letters in the generated passwords.'
complete -c pwgen -s a -l alt-phonics --description 'This option doesn\'t do anything special; it is present only for backwards com…'
complete -c pwgen -s B -l ambiguous --description 'Don\'t use characters that could be confused by the user when printed, such as…'
complete -c pwgen -s c -l capitalize --description 'Include at least one capital letter in the password.'
complete -c pwgen -s C --description 'Print the generated passwords in columns.'
complete -c pwgen -s N -l num-passwords --description 'Generate   num passwords.'
complete -c pwgen -s n -l numerals --description 'Include at least one number in the password.'
complete -c pwgen -s H -l sha1 --description 'Will use the sha1\'s hash of given file and the optional seed to create   pass…'
complete -c pwgen -s h -l help --description 'Print a help message.'
complete -c pwgen -s r -l remove-chars --description 'Don\'t use the specified characters in password.'
complete -c pwgen -s s -l secure --description 'Generate completely random, hard-to-memorize passwords.'
complete -c pwgen -s v -l no-vowels --description 'Generate random passwords that do not contain vowels or numbers that might be…'
complete -c pwgen -s y -l symbols --description 'Include at least one special character in the password.'

