# pyfiglet
# Autogenerated from man page /usr/share/man/man1/pyfiglet.1.gz
complete -c pyfiglet -l version --description 'show program\'s version number and exit.'
complete -c pyfiglet -s h -l help --description 'show this help message and exit.'
complete -c pyfiglet -s f -l font --description 'font to render with (default: future).'
complete -c pyfiglet -s D -l direction --description 'set direction text will be formatted in (default: auto).'
complete -c pyfiglet -s j -l justify --description 'set justification, defaults to print direction.'
complete -c pyfiglet -s w -l width --description 'set terminal width for wrapping/justification (default: 80).'
complete -c pyfiglet -s r -l reverse --description 'shows mirror image of output text.'
complete -c pyfiglet -s F -l flip --description 'flips rendered output text over SEE ALSO toilet (1), figlet (1).'

