# pylupdate5
# Autogenerated from man page /usr/share/man/man1/pylupdate5.1.gz
complete -c pylupdate5 -o help --description 'Show a summary of the options.'
complete -c pylupdate5 -o version --description 'Display the version of pylupdate5 and exit.'
complete -c pylupdate5 -o verbose --description 'Explain what is being done.'
complete -c pylupdate5 -o noobsolete --description 'Drop all obsolete strings.'
complete -c pylupdate5 -o tr-function --description 'Specify name of function that should be used instead of tr().'
complete -c pylupdate5 -o translate-function --description 'Specify name of function that should be used instead of translate().'

