# pyrcc5
# Autogenerated from man page /usr/share/man/man1/pyrcc5.1.gz
complete -c pyrcc5 -o help --description 'Show a summary of the options.'
complete -c pyrcc5 -o version --description 'Display the version number and exit.'
complete -c pyrcc5 -s o --description 'Write the generated output to FILE instead of stdout.'
complete -c pyrcc5 -o threshold --description 'Set the threshold above which files should be compressed.'
complete -c pyrcc5 -o compress --description 'Set the compression level for all input files.'
complete -c pyrcc5 -o root --description 'Search all resource referenced in a . qrc file under PATH.'
complete -c pyrcc5 -o no-compress --description 'Do not compress the resource files at all.'

