# pyuic5
# Autogenerated from man page /usr/share/man/man1/pyuic5.1.gz
complete -c pyuic5 -s h -l help --description 'Show a summary of the options.'
complete -c pyuic5 -l version --description 'Display the pyuic and Qt version numbers and exit.'
complete -c pyuic5 -s p -l preview --description 'Show a preview of the UI instead of generating Python code.'
complete -c pyuic5 -s o -l output --description 'Write the generated Python code to FILE instead of stdout.'
complete -c pyuic5 -s d -l debug --description 'Show detailed debugging information about the UI generation process.'
complete -c pyuic5 -s x -l execute --description 'Generate extra code to test and display the class when executed as a script.'
complete -c pyuic5 -s i -l indent --description 'Set the indentation width to NUM spaces.'
complete -c pyuic5 -l import-from --description 'Generate imports of pyrcc5 generated modules in the style "from PACKAGE impor…'
complete -c pyuic5 -l from-imports --description 'The equivalent of "--import-from=. ".'
complete -c pyuic5 -l resource-suffix --description 'Append SUFFIX to the basename of resource files (default: _rc).'

