# rdf2ihx
# Autogenerated from man page /usr/share/man/man1/rdf2ihx.1.gz
complete -c rdf2ihx -s o --description 'Relocate at origin R relocation-origin .'
complete -c rdf2ihx -s p --description 'Pad segments until their size is a multiple of R segment-alignment .'
complete -c rdf2ihx -s f --description 'Specify the output format.'

