# rdf2srec
# Autogenerated from man page /usr/share/man/man1/rdf2srec.1.gz
complete -c rdf2srec -s o --description 'Relocate at origin R relocation-origin .'
complete -c rdf2srec -s p --description 'Pad segments until their size is a multiple of R segment-alignment .'
complete -c rdf2srec -s f --description 'Specify the output format.'

