# recon-ng
# Autogenerated from man page /usr/share/man/man1/recon-ng.1.gz
complete -c recon-ng -s h -l help --description 'show this help message and exit.'
complete -c recon-ng -s w --description 'load/create a workspace.'
complete -c recon-ng -s r --description 'load commands from a resource file.'
complete -c recon-ng -l no-version --description 'disable version check (by default in Debian).'
complete -c recon-ng -l no-analytics --description 'disable analytics reporting (by default in Debian).'
complete -c recon-ng -l no-marketplace --description 'disable remote module management.'
complete -c recon-ng -l stealth --description 'disable all passive requests (--no-*).'
complete -c recon-ng -s v -l version --description 'displays the current version.'
complete -c recon-ng -l analytics --description 'enable Google analytics reporting.'

