# redsocks
# Autogenerated from man page /usr/share/man/man8/redsocks.8.gz
complete -c redsocks -s p --description 'Write the process ID to pidfile.'
complete -c redsocks -s c --description 'Use config as configuration file.'
complete -c redsocks -s t --description 'Test configuration file syntax.  SEE ALSO iptables (8), /etc/redsocks.'

