# reged
# Autogenerated from man page /usr/share/man/man8/reged.8.gz
complete -c reged -s h --description 'Show summary of options.'
complete -c reged -s x --description 'Export parts of a hive file to a text registry (. reg)  file.'
complete -c reged -s I --description 'Import the content of the input. reg file into the registry file.'
complete -c reged -s e --description 'Interactive edit one or more registry files.'
complete -c reged -s L --description 'Log all changed filenames to /tmp/changed.'
complete -c reged -s C --description 'Automatically save all changes.  Do not prompt the user.'
complete -c reged -s N --description 'Do not allocate more information, only allow the editing of existing values w…'
complete -c reged -s E --description 'Do not expand the hive file (safe mode).'
complete -c reged -s t --description 'Print debug information of allocated blocks.'
complete -c reged -s v --description 'Print verbose information and debug messages.'

