# rlinetd
# Autogenerated from man page /usr/share/man/man8/rlinetd.8.gz
complete -c rlinetd -s d -l debug --description '\\" -d | --debug is a flag to raise the debug level.'
complete -c rlinetd -s h -l help --description '\\" -h | --help will give a brief synopsis of the options.'
complete -c rlinetd -s f -l config --description 'allows the specification of an alternative configuration file to be read.'
complete -c rlinetd -s p -l parser --description 'allows the specification of an alternative parser module to be used when pars…'

