# rq
# Autogenerated from man page /usr/share/man/man1/rq.1.gz
complete -c rq -l version --description 'Show the version and exit.'
complete -c rq -l help --description 'Show this message and exit. SS "Commands:".'

