# sadc
# Autogenerated from man page /usr/share/man/man8/sadc.8.gz
complete -c sadc -s C --description 'When neither the  interval nor the  count parameters are specified, this opti…'
complete -c sadc -s D --description 'Use  saYYYYMMDD instead of  saDD as the standard system activity daily data f…'
complete -c sadc -s F --description 'The creation of  outfile will be forced.'
complete -c sadc -s f --description 'fdatasync() will be used to ensure data is written to disk.'
complete -c sadc -s L --description 'sadc will try to get an exclusive lock on the  outfile before writing to it o…'
complete -c sadc -s S --description 'Possible keywords are DISK, INT, IPV6, POWER, SNMP, XDISK, ALL, and XALL.'
complete -c sadc -s V --description 'Print version number then exit.'

