# sampasswd
# Autogenerated from man page /usr/share/man/man8/sampasswd.8.gz
complete -c sampasswd -s h --description 'Show summary of options.'
complete -c sampasswd -s r --description 'Reset the user\'s password.'
complete -c sampasswd -s a --description 'Reset all the users.'
complete -c sampasswd -s u --description 'User to change.'
complete -c sampasswd -s l --description 'Lists the users in the SAM database.'
complete -c sampasswd -s H --description 'Output human readable output.'
complete -c sampasswd -s N --description 'Do not allocate more information, only allow the editing of existing values w…'
complete -c sampasswd -s E --description 'Do not expand the hive file (safe mode).'
complete -c sampasswd -s t --description 'Print debug information of allocated blocks.'
complete -c sampasswd -s v --description 'Print verbose information and debug messages.'

