# samusrgrp
# Autogenerated from man page /usr/share/man/man8/samusrgrp.8.gz
complete -c samusrgrp -s h --description 'Show summary of options.'
complete -c samusrgrp -s a --description 'The user is added to the group.'
complete -c samusrgrp -s r --description 'The user is removed from the group.'
complete -c samusrgrp -s u --description 'User to change.'
complete -c samusrgrp -s g --description 'Group to change.'
complete -c samusrgrp -s l --description 'Lists the groups in the SAM database.'
complete -c samusrgrp -s L --description 'Lists the groups in the SAM database as well as their members.'
complete -c samusrgrp -s s --description 'Print the machine SID.'
complete -c samusrgrp -s H --description 'Output human readable output.'
complete -c samusrgrp -s N --description 'Do not allocate more information, only allow the editing of existing values w…'
complete -c samusrgrp -s E --description 'Do not expand the hive file (safe mode).'
complete -c samusrgrp -s t --description 'Print debug information of allocated blocks.'
complete -c samusrgrp -s v --description 'Print verbose information and debug messages.'

