# scalpel
# Autogenerated from man page /usr/share/man/man1/scalpel.1.gz
complete -c scalpel -s b --description 'Carve files even if defined footers aren\'t discovered within maximum carve si…'
complete -c scalpel -s c --description 'Chooses which configuration file to use.'
complete -c scalpel -s d --description 'Generate header/footer database; will bypass certain optimizations and discov…'
complete -c scalpel -s m --description 'Generate/update carve coverage blockmap file.'
complete -c scalpel -s h --description 'Show a help screen and exit.'
complete -c scalpel -s i --description 'file is used as a list of input files to examine.'
complete -c scalpel -s o --description 'Recovered files are written to the directory directory.'
complete -c scalpel -s O --description 'Don\'t organize carved files by type.'
complete -c scalpel -s p --description 'Perform image file preview; audit log indicates which files would have been c…'
complete -c scalpel -s q --description 'Carve only when header is cluster-aligned.'
complete -c scalpel -s r --description 'Find only first of overlapping headers/footers [foremost 0. 69 compat mode].'
complete -c scalpel -s s --description 'Skips number bytes in each input file before beginning the search for file he…'
complete -c scalpel -s t --description 'Set directory for coverage blockmap.   **EXPERIMENTAL**.'
complete -c scalpel -s u --description 'Use carve coverage blockmap when carving.'
complete -c scalpel -s V --description 'Show copyright information and exit.'
complete -c scalpel -s v --description 'Enables verbose mode.'

