# scapy3
# Autogenerated from man page /usr/share/man/man1/scapy3.1.gz
complete -c scapy3 -s h --description 'display usage.'
complete -c scapy3 -s d --description 'increase log verbosity.  Can be used many times.'
complete -c scapy3 -s s --description 'use FILE to save/load session values (variables, functions, instances, . ).'
complete -c scapy3 -s p --description 'use PRESTART_FILE instead of $HOME/. scapy_prestart. py as pre-startup file.'
complete -c scapy3 -s P --description 'do not run prestart file.'
complete -c scapy3 -s c --description 'use STARTUP_FILE instead of $HOME/. scapy_startup. py as startup file.'
complete -c scapy3 -s C --description 'do not run startup file.'

