# sdmem
# Autogenerated from man page /usr/share/man/man1/sdmem.1.gz
complete -c sdmem -s f --description 'fast (and insecure mode): no /dev/urandom.'
complete -c sdmem -s l --description 'lessens the security.'
complete -c sdmem -s v --description 'verbose mode NOTE.'

