# sendEmail
# Autogenerated from man page /usr/share/man/man1/sendEmail.1.gz
complete -c sendEmail -s f --description 'from (sender) email address.'
complete -c sendEmail -s t -o cc -o bcc --description '* Message body required via -m, STDIN, or -o message-file=FILE.'
complete -c sendEmail -s u --description 'message subject.'
complete -c sendEmail -s m --description 'message body.'
complete -c sendEmail -s s --description 'smtp mail relay, default is localhost:25.'
complete -c sendEmail -s S --description 'use local sendmail utility (default: /usr/bin/sendmail) instead of network MT…'
complete -c sendEmail -s a --description 'FILE [FILE . ]      file attachment(s).'
complete -c sendEmail -o xu --description 'authentication user (for SMTP authentication).'
complete -c sendEmail -o xp --description 'authentication password (for SMTP authentication).'
complete -c sendEmail -s l --description 'LOGFILE               log to the specified file.'
complete -c sendEmail -s v --description 'verbosity, use multiple times for greater effect.'
complete -c sendEmail -s q --description 'be quiet (no stdout output).'
complete -c sendEmail -s o --description 'see extended help topic "misc" for details.'
complete -c sendEmail -l help --description 'The following extended help topics are available:.'

