# smbinfo
# Autogenerated from man page /usr/share/man/man1/smbinfo.1.gz
complete -c smbinfo -s v --description 'Print version number and exit.'
complete -c smbinfo -s V --description 'Verbose output.'

