# snmptop
# Autogenerated from man page /usr/share/man/man1/snmptop.1.gz
complete -c snmptop -o Cp --description 'Show hrSWRunPath in addition to hrSWRunName.'
complete -c snmptop -o Ca --description 'Show hrSWRunParameters in addition to hrSWRunName.'
complete -c snmptop -o Ct --description 'Sort display by total CPU usage.'
complete -c snmptop -o Cm --description 'Sort display by memory usage.'

