# snmp-check
# Autogenerated from man page /usr/share/man/man1/snmp-check.1.gz
complete -c snmp-check -s p -l port --description '.'
complete -c snmp-check -s c -l community --description '.'
complete -c snmp-check -s v -l version --description '.'
complete -c snmp-check -s w -l write --description '.'
complete -c snmp-check -s d -l disable_tcp --description '.'
complete -c snmp-check -s t -l timeout --description '.'
complete -c snmp-check -s r -l retries --description '.'
complete -c snmp-check -s i -l info --description '.'
complete -c snmp-check -s h -l help --description '.'

