# snmpinform
# Autogenerated from man page /usr/share/man/man1/snmpinform.1.gz
complete -c snmpinform -o Ci --description 'is added to the command line flags of snmptrap, it sends an INFORM-PDU, expec…'

