# snmpcheck
# Autogenerated from man page /usr/share/man/man1/snmpcheck.1.gz
complete -c snmpcheck -s h --description 'Display this message.'
complete -c snmpcheck -s a --description 'check error log file AND hosts specified on command line.'
complete -c snmpcheck -s p --description 'Don\'t try and ping-echo the host first.'
complete -c snmpcheck -s f --description 'Only check for things I can fix.'
complete -c snmpcheck -s x --description 'forces ascii base if $DISPLAY set (instead of tk).'
complete -c snmpcheck -s H --description 'start in hidden mode.   (hides user interface).'
complete -c snmpcheck -s V --description 'sets the initial verbosity level of the command log (def: 1).'
complete -c snmpcheck -s L --description 'Show the log window at startup.'
complete -c snmpcheck -s d --description 'Don\'t start by checking anything.   Just bring up the interface.'
complete -c snmpcheck -s n --description 'Don\'t ever try and fix the problems found.   Just list.'
complete -c snmpcheck -s y --description 'Always fix problems found.'

