# sqlmapapi
# Autogenerated from man page /usr/share/man/man1/sqlmapapi.1.gz
complete -c sqlmapapi -s h -l help --description 'show this help message and exit.'
complete -c sqlmapapi -s s -l server --description 'Run as a REST-JSON API server.'
complete -c sqlmapapi -s c -l client --description 'Run as a REST-JSON API client.'
complete -c sqlmapapi -s H -l host --description 'Host of the REST-JSON API server (default "127. 0. 0. 1").'
complete -c sqlmapapi -s p -l port --description 'Port of the the REST-JSON API server (default 8775).'
complete -c sqlmapapi -l adapter --description 'Server (bottle) adapter to use (default "wsgiref").'
complete -c sqlmapapi -l username --description 'Basic authentication username (optional).'
complete -c sqlmapapi -l password --description 'Basic authentication password (optional).'

