# srch_strings
# Autogenerated from man page /usr/share/man/man1/srch_strings.1.gz
complete -c srch_strings -s a --description 'Scan the entire file, not just the data section.'
complete -c srch_strings -s f --description 'Print the name of the file before each string.'
complete -c srch_strings -s n -o number --description 'Locate and print any NUL-terminated sequence of at least number characters (d…'
complete -c srch_strings -s t --description 'Print the location of the string in base 8, 10 or 16.'
complete -c srch_strings -s o --description 'An alias for --radix=o.'
complete -c srch_strings -s e --description 'Select character size and endianness: s = 7-bit, S = 8-bit, {b,l} = 16-bit, {…'
complete -c srch_strings -s h --description 'Display command line help.'
complete -c srch_strings -s v --description 'Print the program\'s version number.'

