# sshpk-sign
# Autogenerated from man page /usr/share/man/man1/sshpk-sign.1.gz
complete -c sshpk-sign -s v -l verbose --description '  Print extra information about the key and signature to stderr when signing.'
complete -c sshpk-sign -s b -l binary --description '  Don\'t base64-encode the signature before outputting it.'
complete -c sshpk-sign -s i -l identity --description '  Select the key to be used for signing.'
complete -c sshpk-sign -s f -l file --description '  Input file to sign instead of stdin.'
complete -c sshpk-sign -s o -l out --description '  Output file to save signature in instead of stdout.'
complete -c sshpk-sign -s H -l hash --description '  Set the hash algorithm to be used for signing.'
complete -c sshpk-sign -s t -l format --description '  Choose the signature format to use, from asn1, ssh or raw (only for   ED255…'

