# sshpk-verify
# Autogenerated from man page /usr/share/man/man1/sshpk-verify.1.gz
complete -c sshpk-verify -s v -l verbose --description '  Print extra information about the key and signature to stderr when verifyin…'
complete -c sshpk-verify -s i -l identity --description '  Select the key to be used for verification.'
complete -c sshpk-verify -s s -l signature --description '  Supplies the base64-encoded signature to be verified.'
complete -c sshpk-verify -s f -l file --description '  Input file to verify instead of stdin.'
complete -c sshpk-verify -s H -l hash --description '  Set the hash algorithm to be used for signing.'
complete -c sshpk-verify -s t -l format --description '  Choose the signature format to use, from asn1, ssh or raw (only for   ED255…'

