# stunnel4
# Autogenerated from man page /usr/share/man/man8/stunnel4.8.gz
complete -c stunnel4 -o fd --description 'Read the config file from specified file descriptor.'
complete -c stunnel4 -o help --description 'Print stunnel help menu.'
complete -c stunnel4 -o version --description 'Print stunnel version and compile time defaults.'
complete -c stunnel4 -o sockets --description 'Print default socket options.'
complete -c stunnel4 -o options --description 'Print supported \\s-1TLS\\s0 options.'
complete -c stunnel4 -o install --description 'Install \\s-1NT\\s0 Service.'
complete -c stunnel4 -o uninstall --description 'Uninstall \\s-1NT\\s0 Service.'
complete -c stunnel4 -o start --description 'Start \\s-1NT\\s0 Service.'
complete -c stunnel4 -o stop --description 'Stop \\s-1NT\\s0 Service.'
complete -c stunnel4 -o reload --description 'Reload the configuration file of the running \\s-1NT\\s0 Service.'
complete -c stunnel4 -o reopen --description 'Reopen the log file of the running \\s-1NT\\s0 Service.'
complete -c stunnel4 -o exit --description 'Exit an already started stunnel.'

