# tabbed
# Autogenerated from man page /usr/share/man/man1/tabbed.1.gz
complete -c tabbed -s c --description 'close tabbed when the last tab is closed.  Mutually exclusive with -f.'
complete -c tabbed -s d --description 'detaches tabbed from the terminal and prints its XID to stdout.'
complete -c tabbed -s f --description 'fill up tabbed again by spawning the provided command, when the last tab is c…'
complete -c tabbed -s h --description 'will print the usage of tabbed.'
complete -c tabbed -s g --description 'defines the X11 geometry string, which will fixate the height and width of ta…'
complete -c tabbed -s n --description 'will set the WM_CLASS attribute to  name.'
complete -c tabbed -s p --description 'will set the absolute or relative position of where to start a new tab.'
complete -c tabbed -s r --description 'will replace the  narg th argument in  command with the window id, rather tha…'
complete -c tabbed -s s --description 'will disable automatic spawning of the command.'
complete -c tabbed -s t --description 'defines the selected background color.'
complete -c tabbed -s T --description 'defines the selected foreground color.'
complete -c tabbed -s u --description 'defines the normal background color.'
complete -c tabbed -s U --description 'defines the normal foreground color.'
complete -c tabbed -s v --description 'prints version information to stderr, then exits.  USAGE.'

