# tabulate
# Autogenerated from man page /usr/share/man/man1/tabulate.1.gz
complete -c tabulate -s h -l help --description 'show this message.'
complete -c tabulate -s 1 -l header --description 'use the first row of data as a table header.'
complete -c tabulate -s o -l output --description 'print table to FILE (default: stdout).'
complete -c tabulate -s s -l sep --description 'use a custom column separator (default: whitespace).'
complete -c tabulate -s F -l float --description 'floating point number format (default: g).'
complete -c tabulate -s f -l format --description 'set output table format; supported formats: plain, simple, grid, fancy_grid, …'

