# telegram-desktop
# Autogenerated from man page /usr/share/man/man1/telegram-desktop.1.gz
complete -c telegram-desktop -o startintray --description 'Do not show the main window, just start in the system tray.'
complete -c telegram-desktop -o many --description 'Allow multiple instances of the client at the same time.'
complete -c telegram-desktop -o debug --description 'Run in debug mode immediately.  See logs in ~/.'

