# teredo-mire
# Autogenerated from man page /usr/share/man/man1/teredo-mire.1.gz
complete -c teredo-mire -s h -l help --description 'Display some help and exit.'
complete -c teredo-mire -s V -l version --description 'Display program version and exit.'

