# tightvncpasswd
# Autogenerated from man page /usr/share/man/man1/tightvncpasswd.1.gz
complete -c tightvncpasswd -s t --description 'Write passwords into /tmp/$USER-vnc/passwd, creating the /tmp/$USER-vnc/ dire…'
complete -c tightvncpasswd -s f --description 'Only the first eight characters are significant.'

