# udptunnel
# Autogenerated from man page /usr/share/man/man1/udptunnel.1.gz
complete -c udptunnel -s s --description '"Server mode: If udptunnel is invoked with the -s option, it runs in server m…'
complete -c udptunnel -s c --description '"Client mode: If udptunnel is invoked with the -c option, it runs in client m…'
complete -c udptunnel -s r --description '"RTP mode: In order to facilitate tunneling both RTP and RTCP traffic for a m…'

