# update-inetd
# Autogenerated from man page /usr/share/man/man8/update-inetd.8.gz
complete -c update-inetd -l version --description 'Prints version information on standard output and exit successfully.'
complete -c update-inetd -l add --description 'Adds an entry, which should be a line in a  inetd. conf (5) format.'
complete -c update-inetd -l remove --description 'Removes a service.'
complete -c update-inetd -l enable --description 'Enables a service.'
complete -c update-inetd -l disable --description 'Disables a service.  OPTIONS.'

