# vbutil_kernel
# Autogenerated from man page /usr/share/man/man1/vbutil_kernel.1.gz
complete -c vbutil_kernel -l keyblock --description 'Key block in . keyblock format.'
complete -c vbutil_kernel -l signprivate --description 'Private key to sign kernel data, in . vbprivk format.'
complete -c vbutil_kernel -l version --description 'Kernel version.'
complete -c vbutil_kernel -l vmlinuz --description 'Linux kernel bzImage file.'
complete -c vbutil_kernel -l bootloader --description 'Bootloader stub.'
complete -c vbutil_kernel -l config --description 'Command line file.'
complete -c vbutil_kernel -l arch --description 'Cpu architecture (default x86) P Optional:.'
complete -c vbutil_kernel -l kloadaddr --description 'Assign kernel body load address.'
complete -c vbutil_kernel -l pad --description 'Verification padding size in bytes.'
complete -c vbutil_kernel -l vblockonly --description 'Emit just the verification blob.'
complete -c vbutil_kernel -l flags --description 'Flags to be passed in the header . PP OR .'
complete -c vbutil_kernel -l oldblob --description 'Previously packed kernel blob (including verification blob) P Optional:.'
complete -c vbutil_kernel -l signpubkey --description 'Public key to verify kernel keyblock, in . vbpubk format.'
complete -c vbutil_kernel -l verbose --description 'Print a more detailed report.'
complete -c vbutil_kernel -l minversion --description 'Minimum combined kernel key version . PP OR .'
complete -c vbutil_kernel -l vmlinuz-out --description 'vmlinuz image output file .'

