# vncpasswd
# Autogenerated from man page /usr/share/man/man1/vncpasswd.1.gz
complete -c vncpasswd -s t --description 'Write passwords into /tmp/$USER-vnc/passwd, creating the /tmp/$USER-vnc/ dire…'
complete -c vncpasswd -s f --description 'Only the first eight characters are significant.'

