# vncserver
# Autogenerated from man page /usr/share/man/man1/vncserver.1.gz
complete -c vncserver -o geometry --description 'Set desktop width and height.'
complete -c vncserver -o depth --description 'Set the colour depth of the visual to provide, in bits per pixel.'
complete -c vncserver -o pixelformat --description 'Set colour format for pixels representation.'
complete -c vncserver -o name --description 'This specifies the name of the desktop.'
complete -c vncserver -o clean --description 'This option can be used in conjunction with.'
complete -c vncserver -o kill --description 'Stops the session running on the specified display.'
complete -c vncserver -o nevershared --description 'Never allow shared desktops.'
complete -c vncserver -o alwaysshared --description 'Always allow shared desktops.'
complete -c vncserver -o basehttpport --description 'The base http port to use for the java client applet (you have to install the…'
complete -c vncserver -o httpport --description 'The http port to use for the java client applet (you have to install the tigh…'
complete -c vncserver -o help --description 'Prints a short usage notice to stderr.  EXAMPLES.'

