# westcos-tool
# Autogenerated from man page /usr/share/man/man1/westcos-tool.1.gz
complete -c westcos-tool -l change-pin -s n --description 'Changes a PIN stored on the card.'
complete -c westcos-tool -l certificate -s t --description 'Write certificate file file in PEM format to the card.'
complete -c westcos-tool -l finalize -s f --description 'Finalize the card.'
complete -c westcos-tool -l generate-key -s g --description 'Generate a private key on the card.'
complete -c westcos-tool -l help -s h --description 'Print help message on screen.'
complete -c westcos-tool -l install-pin -s i --description 'Install PIN file in on the card.  You must provide a PIN value with -x.'
complete -c westcos-tool -l key-length -s l --description 'Change the length of private key.  Use with -g.'
complete -c westcos-tool -l overwrite-key -s o --description 'Overwrite the key if there is already a key on the card.'
complete -c westcos-tool -l pin-value -s x --description 'Set value of PIN.'
complete -c westcos-tool -l puk-value -s y --description 'set value of PUK (or value of new PIN for change PIN command see -n).'
complete -c westcos-tool -l read-file -s j --description 'Read the file filename from the card.'
complete -c westcos-tool -l reader -s r --description 'Number of the reader to use.'
complete -c westcos-tool -l unblock-pin -s u --description 'Unblocks a PIN stored on the card.'
complete -c westcos-tool -l verbose -s v --description 'Causes westcos-tool to be more verbose.'
complete -c westcos-tool -l wait -s w --description 'Wait for a card to be inserted.'
complete -c westcos-tool -l write-file -s k --description 'Put the file with name filename from disk to card.'

