# winexe
# Autogenerated from man page /usr/share/man/man1/winexe.1.gz
complete -c winexe -s '?' -l help --description 'Display help text.'
complete -c winexe -s A -l authentication-file --description 'Get credentials from FILE.'
complete -c winexe -s d -l debuglevel --description 'Set the level of debug output to LOGLEVEL.'
complete -c winexe -l interactive --description 'Allow (1) or disallow (0) interative mode.'
complete -c winexe -s k -l kerberos --description 'Use Kerberos, yes or no?.'
complete -c winexe -s N -l no-pass --description 'Do not prompt for a password.'
complete -c winexe -l ostype --description 'Install 32-bit (0); 64-bit (1); or automatically chosen (2) version of the wi…'
complete -c winexe -l reinstall --description 'Uninstall the winexe service from the remote machine and install it again bef…'
complete -c winexe -l runas --description 'Run the desired command under Windows account USERNAME with optional DOMAIN a…'
complete -c winexe -l runas-file --description 'Run the desired command under the account defined in FILE.'
complete -c winexe -l system --description 'Use the "SYSTEM" account.  If --runas is given then this option is ignored.'
complete -c winexe -s U -l user --description 'Set the login USERNAME and optionally also DOMAIN and PASSWORD.'
complete -c winexe -l uninstall --description 'Uninstall the winexe service from the remote machine after using it to execut…'

