# xcb
# Autogenerated from man page /usr/share/man/man1/xcb.1.gz
complete -c xcb -s l --description 'This option controls the geometry arrangement of xcb\'s subwindows.'
complete -c xcb -s n --description 'Create count cut buffers.  Count can be any integer greater than zero.'
complete -c xcb -s u --description 'Use utf-8 instead of the current locale settings when executing in task mode …'
complete -c xcb -s V --description 'Print the xcb release version number and exit immediately. LP.'
complete -c xcb -s p --description 'Print the contents of the listed buffer(s) on stdout.'
complete -c xcb -s r --description 'Rotate the buffers by count positions.'
complete -c xcb -s s --description 'Store the data from stdin in the listed buffer(s).'
complete -c xcb -s S --description 'options causes xcb to execute in task mode, described above.'

