# xfpm-power-backlight-helper
# Autogenerated from man page /usr/share/man/man8/xfpm-power-backlight-helper.8.gz
complete -c xfpm-power-backlight-helper -s h -l help --description 'Show help options . SS "Application Options:".'
complete -c xfpm-power-backlight-helper -l set-brightness --description 'Set the current brightness.'
complete -c xfpm-power-backlight-helper -l get-brightness --description 'Get the current brightness.'
complete -c xfpm-power-backlight-helper -l get-max-brightness --description 'Get the number of brightness levels supported SEE ALSO.'

